### ISSUE TITLE
[Question] Problem Installing Django 1.8. Python 2.7

### ISSUE THREAD

**Issue by mykljohn** [juanpex/django-model-report#73]
I following the installation, but I get the following error: ImportError: No module named related

What have I missed?  Thanks.  here's the traceback.

2016-02-11 23:23:07,784 :Traceback (most recent call last):
2016-02-11 23:23:07,785 :  File "/bin/user_wsgi_wrapper.py", line 134, in **call**
2016-02-11 23:23:07,785 :    self.error_log_file.logger.exception("Error running WSGI application")
2016-02-11 23:23:07,785 :  File "/usr/lib/python2.7/logging/**init**.py", line 1185, in exception
2016-02-11 23:23:07,785 :    self.error(msg, _args, *_kwargs)
2016-02-11 23:23:07,785 :  File "/usr/lib/python2.7/logging/**init**.py", line 1178, in error
2016-02-11 23:23:07,786 :    self._log(ERROR, msg, args, **kwargs)
2016-02-11 23:23:07,786 :  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
2016-02-11 23:23:07,786 :    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
2016-02-11 23:23:07,786 :  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
2016-02-11 23:23:07,786 :    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
2016-02-11 23:23:07,786 :  File "/usr/lib/python2.7/logging/**init**.py", line 284, in **init**
2016-02-11 23:23:07,787 :    self.threadName = threading.current_thread().name
2016-02-11 23:23:07,787 :  File "/usr/lib/python2.7/threading.py", line 1160, in currentThread
2016-02-11 23:23:07,787 :    return _active[_get_ident()]
2016-02-11 23:23:07,787 :  File "/bin/user_wsgi_wrapper.py", line 126, in __call__
2016-02-11 23:23:07,787 :    app_iterator = self.app(environ, start_response)
2016-02-11 23:23:07,787 :  File "/bin/user_wsgi_wrapper.py", line 140, in import_error_application
2016-02-11 23:23:07,787 :    raise e
2016-02-11 23:23:07,788 :ImportError: No module named related

**Comment by phoebebright** [comment]
This is still an issue with the version installed via pip (as at 9mar16) but the fix has been made in the repo.

**Comment by mykljohn** [comment]
How do I install from the repo?  I've downloaded the latest version, do I upload it and then pip install the downloaded version?

**Comment by mykljohn** [comment]
@phoebebright  I'm still having trouble here.  I got past this issue, but now I'm getting Template not found model_report/report.html   But in the trace back, it says it was found...I'm confused.  any help?
