### ISSUE TITLE
The installation of django-report-model gives error in python3 due to the dependency BeautifulSoup

### ISSUE THREAD

**Issue by anuragiiits** [juanpex/django-model-report#88]
https://github.com/juanpex/django-model-report/blob/6d2fa6175149eb95a1a9829ae3412f38dabb1a32/requirements.txt#L4

Here is the error:
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\pip-install-62dcohsu\BeautifulSoup\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
```

I am not sure but a fix can be using beautifulsoup4 which is supported by python 3.

**Comment by anuragiiits** [comment]
Sorry, I just realized there is no support for python 3 yet.
